import { CustomResource, CustomResourceArgs } from "@pulumi/kubernetes/apiextensions"
import * as pulumi from "@pulumi/pulumi"

/**
 * This type represents the constructor of the given class, so can be used to say "this class extends X class"
 * @example
 *  type extendsConstruct = Constructor<Construct>
 * @template T
 */
export type Constructor<T> = new (...args: any[]) => T

export type PropsFromGeneratedInterface<T> = Omit<T, 'apiVersion' | 'kind'> & {
  apiVersion?: string
  kind?: string
}

export interface generateCustomResourceClassOptions {
  /**
   * Default properties for the resource.
   * This should include the 'apiVersion' and 'kind' at a minimum.
   */
  properties: {
    apiVersion: string
    kind: string
    group: string
    [key: string]: any
  }
}

/**
 * Used to generate a custom resource class from CRDs that have been generated by crdtotypes.
 * @internal
 */
export function generateCustomResourceClass<generatedInterface extends CustomResourceArgs>({ properties: { apiVersion, version, kind, group, ...rest } }: generateCustomResourceClassOptions) {

  type generatedResourceProps = PropsFromGeneratedInterface<generatedInterface>
  type generatedResourceType<T extends Constructor<pulumi.Resource>> = typeof CustomResource & {
    new (name: string, args: generatedResourceProps, opts?: pulumi.ComponentResourceOptions): T
  }

  // Type generator doesn't always include the apiVersion
  if (!apiVersion) {
    apiVersion = version
  }

  // Kube throws if the apiVersion doesn't include a group
  if (!apiVersion!.includes('/')) {
    apiVersion = `${group}/${apiVersion}`
  }

  const generatedClass = class extends CustomResource{
    constructor(name: string, args: generatedResourceProps, opts?: pulumi.ComponentResourceOptions) {
      super(`kubernetes:CustomResource:${group}:${kind}/${name}`, {
        apiVersion,
        kind,
        ...rest,
        ...args
      }, opts)
    }
  }

  // This kind of sucks but it's _really_ hard to get to work otherwise due to pulumi components having private properties
  return generatedClass as generatedResourceType<typeof CustomResource>
}
