// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * EventSubscription defines filters for events
 *
 * @export
 */
export interface CloudEventSourceSpecEventSubscription {
  /** excludedEventTypes
   * CloudEventType contains the list of cloudevent types
   *
   * @required {false}
   * @originalType {string}
   */
  excludedEventTypes?: ('keda.scaledobject.ready.v1' | 'keda.scaledobject.failed.v1')[];
  /** includedEventTypes
   * CloudEventType contains the list of cloudevent types
   *
   * @required {false}
   * @originalType {string}
   */
  includedEventTypes?: ('keda.scaledobject.ready.v1' | 'keda.scaledobject.failed.v1')[];
}
