// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { CloudEventSourceSpecAuthenticationRef } from './CloudEventSourceSpecAuthenticationRef';
import { CloudEventSourceSpecDestination } from './CloudEventSourceSpecDestination';
import { CloudEventSourceSpecEventSubscription } from './CloudEventSourceSpecEventSubscription';

/**
 * CloudEventSourceSpec defines the spec of CloudEventSource
 *
 * @export
 */
export interface CloudEventSourceSpec {
  /** authenticationRef
   * AuthenticationRef points to the TriggerAuthentication or ClusterTriggerAuthentication object that
is used to authenticate the scaler with the environment
   *
   * @required {false}
   */
  authenticationRef?: CloudEventSourceSpecAuthenticationRef;
  /** clusterName
   *
   * @required {false}
   */
  clusterName?: string;
  /** destination
   * Destination defines the various ways to emit events
   *
   * @required {true}
   */
  destination: CloudEventSourceSpecDestination;
  /** eventSubscription
   * EventSubscription defines filters for events
   *
   * @required {false}
   */
  eventSubscription?: CloudEventSourceSpecEventSubscription;
}
