// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { CloudEventSourceSpecDestinationAzureEventGridTopic } from './CloudEventSourceSpecDestinationAzureEventGridTopic';
import { CloudEventSourceSpecDestinationHttp } from './CloudEventSourceSpecDestinationHttp';

/**
 * Destination defines the various ways to emit events
 *
 * @export
 */
export interface CloudEventSourceSpecDestination {
  /** azureEventGridTopic
   *
   * @required {false}
   */
  azureEventGridTopic?: CloudEventSourceSpecDestinationAzureEventGridTopic;
  /** http
   *
   * @required {false}
   */
  http?: CloudEventSourceSpecDestinationHttp;
}
