// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ClusterTriggerAuthenticationSpecAzureKeyVaultCloud } from './ClusterTriggerAuthenticationSpecAzureKeyVaultCloud';
import { ClusterTriggerAuthenticationSpecAzureKeyVaultCredentials } from './ClusterTriggerAuthenticationSpecAzureKeyVaultCredentials';
import { ClusterTriggerAuthenticationSpecAzureKeyVaultPodIdentity } from './ClusterTriggerAuthenticationSpecAzureKeyVaultPodIdentity';
import { ClusterTriggerAuthenticationSpecAzureKeyVaultSecrets } from './ClusterTriggerAuthenticationSpecAzureKeyVaultSecrets';

/**
 * AzureKeyVault is used to authenticate using Azure Key Vault
 *
 * @export
 */
export interface ClusterTriggerAuthenticationSpecAzureKeyVault {
  /** cloud
   *
   * @required {false}
   */
  cloud?: ClusterTriggerAuthenticationSpecAzureKeyVaultCloud;
  /** credentials
   *
   * @required {false}
   */
  credentials?: ClusterTriggerAuthenticationSpecAzureKeyVaultCredentials;
  /** podIdentity
   * AuthPodIdentity allows users to select the platform native identity
mechanism
   *
   * @required {false}
   */
  podIdentity?: ClusterTriggerAuthenticationSpecAzureKeyVaultPodIdentity;
  /** secrets
   *
   * @required {true}
   */
  secrets: ClusterTriggerAuthenticationSpecAzureKeyVaultSecrets[];
  /** vaultUri
   *
   * @required {true}
   */
  vaultUri: string;
}
