// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ClusterTriggerAuthenticationSpecAwsSecretManagerCredentials } from './ClusterTriggerAuthenticationSpecAwsSecretManagerCredentials';
import { ClusterTriggerAuthenticationSpecAwsSecretManagerPodIdentity } from './ClusterTriggerAuthenticationSpecAwsSecretManagerPodIdentity';
import { ClusterTriggerAuthenticationSpecAwsSecretManagerSecrets } from './ClusterTriggerAuthenticationSpecAwsSecretManagerSecrets';

/**
 * AwsSecretManager is used to authenticate using AwsSecretManager
 *
 * @export
 */
export interface ClusterTriggerAuthenticationSpecAwsSecretManager {
  /** credentials
   *
   * @required {false}
   */
  credentials?: ClusterTriggerAuthenticationSpecAwsSecretManagerCredentials;
  /** podIdentity
   * AuthPodIdentity allows users to select the platform native identity
mechanism
   *
   * @required {false}
   */
  podIdentity?: ClusterTriggerAuthenticationSpecAwsSecretManagerPodIdentity;
  /** region
   *
   * @required {false}
   */
  region?: string;
  /** secrets
   *
   * @required {true}
   */
  secrets: ClusterTriggerAuthenticationSpecAwsSecretManagerSecrets[];
}
