// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ClusterTriggerAuthenticationSpecAwsSecretManager } from './ClusterTriggerAuthenticationSpecAwsSecretManager';
import { ClusterTriggerAuthenticationSpecAzureKeyVault } from './ClusterTriggerAuthenticationSpecAzureKeyVault';
import { ClusterTriggerAuthenticationSpecConfigMapTargetRef } from './ClusterTriggerAuthenticationSpecConfigMapTargetRef';
import { ClusterTriggerAuthenticationSpecEnv } from './ClusterTriggerAuthenticationSpecEnv';
import { ClusterTriggerAuthenticationSpecGcpSecretManager } from './ClusterTriggerAuthenticationSpecGcpSecretManager';
import { ClusterTriggerAuthenticationSpecHashiCorpVault } from './ClusterTriggerAuthenticationSpecHashiCorpVault';
import { ClusterTriggerAuthenticationSpecPodIdentity } from './ClusterTriggerAuthenticationSpecPodIdentity';
import { ClusterTriggerAuthenticationSpecSecretTargetRef } from './ClusterTriggerAuthenticationSpecSecretTargetRef';

/**
 * TriggerAuthenticationSpec defines the various ways to authenticate
 *
 * @export
 */
export interface ClusterTriggerAuthenticationSpec {
  /** awsSecretManager
   * AwsSecretManager is used to authenticate using AwsSecretManager
   *
   * @required {false}
   */
  awsSecretManager?: ClusterTriggerAuthenticationSpecAwsSecretManager;
  /** azureKeyVault
   * AzureKeyVault is used to authenticate using Azure Key Vault
   *
   * @required {false}
   */
  azureKeyVault?: ClusterTriggerAuthenticationSpecAzureKeyVault;
  /** configMapTargetRef
   * AuthConfigMapTargetRef is used to authenticate using a reference to a config map
   *
   * @required {false}
   */
  configMapTargetRef?: ClusterTriggerAuthenticationSpecConfigMapTargetRef[];
  /** env
   * AuthEnvironment is used to authenticate using environment variables
in the destination ScaleTarget spec
   *
   * @required {false}
   */
  env?: ClusterTriggerAuthenticationSpecEnv[];
  /** gcpSecretManager
   *
   * @required {false}
   */
  gcpSecretManager?: ClusterTriggerAuthenticationSpecGcpSecretManager;
  /** hashiCorpVault
   * HashiCorpVault is used to authenticate using Hashicorp Vault
   *
   * @required {false}
   */
  hashiCorpVault?: ClusterTriggerAuthenticationSpecHashiCorpVault;
  /** podIdentity
   * AuthPodIdentity allows users to select the platform native identity
mechanism
   *
   * @required {false}
   */
  podIdentity?: ClusterTriggerAuthenticationSpecPodIdentity;
  /** secretTargetRef
   * AuthSecretTargetRef is used to authenticate using a reference to a secret
   *
   * @required {false}
   */
  secretTargetRef?: ClusterTriggerAuthenticationSpecSecretTargetRef[];
}
