// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

export interface ClusterTriggerAuthenticationSpecAzureKeyVaultCloud {
  /** activeDirectoryEndpoint
   *
   * @required {false}
   */
  activeDirectoryEndpoint?: string;
  /** keyVaultResourceURL
   *
   * @required {false}
   */
  keyVaultResourceURL?: string;
  /** type
   *
   * @required {true}
   */
  type: string;
}
