// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ClusterTriggerAuthenticationSpecAwsSecretManagerCredentialsAccessKeyValueFrom } from './ClusterTriggerAuthenticationSpecAwsSecretManagerCredentialsAccessKeyValueFrom';

export interface ClusterTriggerAuthenticationSpecAwsSecretManagerCredentialsAccessKey {
  /** valueFrom
   *
   * @required {true}
   */
  valueFrom: ClusterTriggerAuthenticationSpecAwsSecretManagerCredentialsAccessKeyValueFrom;
}
