// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

export interface ClusterTriggerAuthenticationSpecHashiCorpVaultSecretsPkiData {
  /** altNames
   *
   * @required {false}
   */
  altNames?: string;
  /** commonName
   *
   * @required {false}
   */
  commonName?: string;
  /** format
   *
   * @required {false}
   */
  format?: string;
  /** ipSans
   *
   * @required {false}
   */
  ipSans?: string;
  /** otherSans
   *
   * @required {false}
   */
  otherSans?: string;
  /** ttl
   *
   * @required {false}
   */
  ttl?: string;
  /** uriSans
   *
   * @required {false}
   */
  uriSans?: string;
}
