// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ClusterTriggerAuthenticationSpecAwsSecretManagerCredentialsAccessKey } from './ClusterTriggerAuthenticationSpecAwsSecretManagerCredentialsAccessKey';
import { ClusterTriggerAuthenticationSpecAwsSecretManagerCredentialsAccessSecretKey } from './ClusterTriggerAuthenticationSpecAwsSecretManagerCredentialsAccessSecretKey';
import { ClusterTriggerAuthenticationSpecAwsSecretManagerCredentialsAccessToken } from './ClusterTriggerAuthenticationSpecAwsSecretManagerCredentialsAccessToken';

export interface ClusterTriggerAuthenticationSpecAwsSecretManagerCredentials {
  /** accessKey
   *
   * @required {true}
   */
  accessKey: ClusterTriggerAuthenticationSpecAwsSecretManagerCredentialsAccessKey;
  /** accessSecretKey
   *
   * @required {true}
   */
  accessSecretKey: ClusterTriggerAuthenticationSpecAwsSecretManagerCredentialsAccessSecretKey;
  /** accessToken
   *
   * @required {false}
   */
  accessToken?: ClusterTriggerAuthenticationSpecAwsSecretManagerCredentialsAccessToken;
}
