// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * TriggerAuthenticationStatus defines the observed state of TriggerAuthentication
 *
 * @export
 */
export interface ClusterTriggerAuthenticationStatus {
  /** scaledjobs
   *
   * @required {false}
   */
  scaledjobs?: string;
  /** scaledobjects
   *
   * @required {false}
   */
  scaledobjects?: string;
}
