// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

export interface ClusterTriggerAuthenticationSpecGcpSecretManagerSecrets {
  /** id
   *
   * @required {true}
   */
  id: string;
  /** parameter
   *
   * @required {true}
   */
  parameter: string;
  /** version
   *
   * @required {false}
   */
  version?: string;
}
