// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ClusterTriggerAuthenticationSpecGcpSecretManagerCredentials } from './ClusterTriggerAuthenticationSpecGcpSecretManagerCredentials';
import { ClusterTriggerAuthenticationSpecGcpSecretManagerPodIdentity } from './ClusterTriggerAuthenticationSpecGcpSecretManagerPodIdentity';
import { ClusterTriggerAuthenticationSpecGcpSecretManagerSecrets } from './ClusterTriggerAuthenticationSpecGcpSecretManagerSecrets';

export interface ClusterTriggerAuthenticationSpecGcpSecretManager {
  /** credentials
   *
   * @required {false}
   */
  credentials?: ClusterTriggerAuthenticationSpecGcpSecretManagerCredentials;
  /** podIdentity
   * AuthPodIdentity allows users to select the platform native identity
mechanism
   *
   * @required {false}
   */
  podIdentity?: ClusterTriggerAuthenticationSpecGcpSecretManagerPodIdentity;
  /** secrets
   *
   * @required {true}
   */
  secrets: ClusterTriggerAuthenticationSpecGcpSecretManagerSecrets[];
}
