// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * secretRef is name of the authentication secret for RBDUser. If provided
overrides keyring.
Default is nil.
More info: https:&#x2F;&#x2F;examples.k8s.io&#x2F;volumes&#x2F;rbd&#x2F;README.md#how-to-use-it
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecVolumesRbdSecretRef {
  /** name
   * Name of the referent.
More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
TODO: Add other useful fields. apiVersion, kind, uid?
   *
   * @required {false}
   */
  name?: string;
}
