// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * VolumeMount describes a mounting of a Volume within a container.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecContainersVolumeMounts {
  /** mountPath
   * Path within the container at which the volume should be mounted.  Must
not contain ':'.
   *
   * @required {true}
   */
  mountPath: string;
  /** mountPropagation
   * mountPropagation determines how mounts are propagated from the host
to container and the other way around.
When not set, MountPropagationNone is used.
This field is beta in 1.10.
   *
   * @required {false}
   */
  mountPropagation?: string;
  /** name
   * This must match the Name of a Volume.
   *
   * @required {true}
   */
  name: string;
  /** readOnly
   * Mounted read-only if true, read-write otherwise (false or unspecified).
Defaults to false.
   *
   * @required {false}
   */
  readOnly?: boolean;
  /** subPath
   * Path within the volume from which the container's volume should be mounted.
Defaults to "" (volume's root).
   *
   * @required {false}
   */
  subPath?: string;
  /** subPathExpr
   * Expanded path within the volume from which the container's volume should be mounted.
Behaves similarly to SubPath but environment variable references $(VAR_NAME) are expanded using the container's environment.
Defaults to "" (volume's root).
SubPathExpr and SubPath are mutually exclusive.
   *
   * @required {false}
   */
  subPathExpr?: string;
}
