// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * The capabilities to add&#x2F;drop when running containers.
Defaults to the default set of capabilities granted by the container runtime.
Note that this field cannot be set when spec.os.name is windows.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecInitContainersSecurityContextCapabilities {
  /** add
   * Capability represent POSIX capabilities type
   *
   * @required {false}
   */
  add?: string[];
  /** drop
   * Capability represent POSIX capabilities type
   *
   * @required {false}
   */
  drop?: string[];
}
