// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * Sysctl defines a kernel parameter to be set
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecSecurityContextSysctls {
  /** name
   * Name of a property to set
   *
   * @required {true}
   */
  name: string;
  /** value
   * Value of a property to set
   *
   * @required {true}
   */
  value: string;
}
