// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledObjectSpecAdvancedHorizontalPodAutoscalerConfigBehavior } from './ScaledObjectSpecAdvancedHorizontalPodAutoscalerConfigBehavior';

/**
 * HorizontalPodAutoscalerConfig specifies horizontal scale config
 *
 * @export
 */
export interface ScaledObjectSpecAdvancedHorizontalPodAutoscalerConfig {
  /** behavior
   * HorizontalPodAutoscalerBehavior configures the scaling behavior of the target
in both Up and Down directions (scaleUp and scaleDown fields respectively).
   *
   * @required {false}
   */
  behavior?: ScaledObjectSpecAdvancedHorizontalPodAutoscalerConfigBehavior;
  /** name
   *
   * @required {false}
   */
  name?: string;
}
