// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecJobTargetRefTemplateSpecContainersLivenessProbeExec } from './ScaledJobSpecJobTargetRefTemplateSpecContainersLivenessProbeExec';
import { ScaledJobSpecJobTargetRefTemplateSpecContainersLivenessProbeGrpc } from './ScaledJobSpecJobTargetRefTemplateSpecContainersLivenessProbeGrpc';
import { ScaledJobSpecJobTargetRefTemplateSpecContainersLivenessProbeHttpGet } from './ScaledJobSpecJobTargetRefTemplateSpecContainersLivenessProbeHttpGet';
import { ScaledJobSpecJobTargetRefTemplateSpecContainersLivenessProbeTcpSocket } from './ScaledJobSpecJobTargetRefTemplateSpecContainersLivenessProbeTcpSocket';

/**
 * Periodic probe of container liveness.
Container will be restarted if the probe fails.
Cannot be updated.
More info: https:&#x2F;&#x2F;kubernetes.io&#x2F;docs&#x2F;concepts&#x2F;workloads&#x2F;pods&#x2F;pod-lifecycle#container-probes
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecContainersLivenessProbe {
  /** exec
   * Exec specifies the action to take.
   *
   * @required {false}
   */
  exec?: ScaledJobSpecJobTargetRefTemplateSpecContainersLivenessProbeExec;
  /** failureThreshold
   * Minimum consecutive failures for the probe to be considered failed after having succeeded.
Defaults to 3. Minimum value is 1.
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  failureThreshold?: number;
  /** grpc
   * GRPC specifies an action involving a GRPC port.
   *
   * @required {false}
   */
  grpc?: ScaledJobSpecJobTargetRefTemplateSpecContainersLivenessProbeGrpc;
  /** httpGet
   * HTTPGet specifies the http request to perform.
   *
   * @required {false}
   */
  httpGet?: ScaledJobSpecJobTargetRefTemplateSpecContainersLivenessProbeHttpGet;
  /** initialDelaySeconds
   * Number of seconds after the container has started before liveness probes are initiated.
More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  initialDelaySeconds?: number;
  /** periodSeconds
   * How often (in seconds) to perform the probe.
Default to 10 seconds. Minimum value is 1.
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  periodSeconds?: number;
  /** successThreshold
   * Minimum consecutive successes for the probe to be considered successful after having failed.
Defaults to 1. Must be 1 for liveness and startup. Minimum value is 1.
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  successThreshold?: number;
  /** tcpSocket
   * TCPSocket specifies an action involving a TCP port.
   *
   * @required {false}
   */
  tcpSocket?: ScaledJobSpecJobTargetRefTemplateSpecContainersLivenessProbeTcpSocket;
  /** terminationGracePeriodSeconds
   * Optional duration in seconds the pod needs to terminate gracefully upon probe failure.
The grace period is the duration in seconds after the processes running in the pod are sent
a termination signal and the time when the processes are forcibly halted with a kill signal.
Set this value longer than the expected cleanup time for your process.
If this value is nil, the pod's terminationGracePeriodSeconds will be used. Otherwise, this
value overrides the value provided by the pod spec.
Value must be non-negative integer. The value zero indicates stop immediately via
the kill signal (no opportunity to shut down).
This is a beta field and requires enabling ProbeTerminationGracePeriod feature gate.
Minimum value is 1. spec.terminationGracePeriodSeconds is used if unset.
   *
   * @required {false}
   * @format {int64}
   * @originalType {integer}
   */
  terminationGracePeriodSeconds?: number;
  /** timeoutSeconds
   * Number of seconds after which the probe times out.
Defaults to 1 second. Minimum value is 1.
More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  timeoutSeconds?: number;
}
