// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecJobTargetRefTemplateSpec } from './ScaledJobSpecJobTargetRefTemplateSpec';

/**
 * Describes the pod that will be created when executing a job.
The only allowed template.spec.restartPolicy values are &quot;Never&quot; or &quot;OnFailure&quot;.
More info: https:&#x2F;&#x2F;kubernetes.io&#x2F;docs&#x2F;concepts&#x2F;workloads&#x2F;controllers&#x2F;jobs-run-to-completion&#x2F;
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplate {
  /** metadata
   * Standard object's metadata.
More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
   *
   * @required {false}
   * @originalType {not defined}
   */
  metadata?: unknown | null;
  /** spec
   * Specification of the desired behavior of the pod.
More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
   *
   * @required {false}
   */
  spec?: ScaledJobSpecJobTargetRefTemplateSpec;
}
