// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * HostAlias holds the mapping between IP and hostnames that will be injected as an entry in the
pod&#39;s hosts file.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecHostAliases {
  /** hostnames
   *
   * @required {false}
   */
  hostnames?: string[];
  /** ip
   * IP address of the host file entry.
   *
   * @required {false}
   */
  ip?: string;
}
