// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * vsphereVolume represents a vSphere volume attached and mounted on kubelets host machine
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecVolumesVsphereVolume {
  /** fsType
   * fsType is filesystem type to mount.
Must be a filesystem type supported by the host operating system.
Ex. "ext4", "xfs", "ntfs". Implicitly inferred to be "ext4" if unspecified.
   *
   * @required {false}
   */
  fsType?: string;
  /** storagePolicyID
   * storagePolicyID is the storage Policy Based Management (SPBM) profile ID associated with the StoragePolicyName.
   *
   * @required {false}
   */
  storagePolicyID?: string;
  /** storagePolicyName
   * storagePolicyName is the storage Policy Based Management (SPBM) profile name.
   *
   * @required {false}
   */
  storagePolicyName?: string;
  /** volumePath
   * volumePath is the path that identifies vSphere volume vmdk
   *
   * @required {true}
   */
  volumePath: string;
}
