// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecJobTargetRefTemplateSpecResourceClaimsSource } from './ScaledJobSpecJobTargetRefTemplateSpecResourceClaimsSource';

/**
 * PodResourceClaim references exactly one ResourceClaim through a ClaimSource.
It adds a name to it that uniquely identifies the ResourceClaim inside the Pod.
Containers that need access to the ResourceClaim reference it with this name.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecResourceClaims {
  /** name
   * Name uniquely identifies this resource claim inside the pod.
This must be a DNS_LABEL.
   *
   * @required {true}
   */
  name: string;
  /** source
   * Source describes where to find the ResourceClaim.
   *
   * @required {false}
   */
  source?: ScaledJobSpecJobTargetRefTemplateSpecResourceClaimsSource;
}
