// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesClusterTrustBundleLabelSelectorMatchExpressions } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesClusterTrustBundleLabelSelectorMatchExpressions';

/**
 * Select all ClusterTrustBundles that match this label selector.  Only has
effect if signerName is set.  Mutually-exclusive with name.  If unset,
interpreted as &quot;match nothing&quot;.  If set but empty, interpreted as &quot;match
everything&quot;.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesClusterTrustBundleLabelSelector {
  /** matchExpressions
   * A label selector requirement is a selector that contains values, a key, and an operator that
relates the key and values.
   *
   * @required {false}
   */
  matchExpressions?: ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesClusterTrustBundleLabelSelectorMatchExpressions[];
  /** matchLabels
   * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
map is equivalent to an element of matchExpressions, whose key field is "key", the
operator is "In", and the values array contains only "value". The requirements are ANDed.
   *
   * @required {false}
   * @originalType {ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesClusterTrustBundleLabelSelectorMatchLabels}
   */
  matchLabels?: {[key: string]: string};
}
