// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * fc represents a Fibre Channel resource that is attached to a kubelet&#39;s host machine and then exposed to the pod.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecVolumesFc {
  /** fsType
   * fsType is the filesystem type to mount.
Must be a filesystem type supported by the host operating system.
Ex. "ext4", "xfs", "ntfs". Implicitly inferred to be "ext4" if unspecified.
TODO: how do we prevent errors in the filesystem from compromising the machine
   *
   * @required {false}
   */
  fsType?: string;
  /** lun
   * lun is Optional: FC target lun number
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  lun?: number;
  /** readOnly
   * readOnly is Optional: Defaults to false (read/write). ReadOnly here will force
the ReadOnly setting in VolumeMounts.
   *
   * @required {false}
   */
  readOnly?: boolean;
  /** targetWWNs
   *
   * @required {false}
   */
  targetWWNs?: string[];
  /** wwids
   *
   * @required {false}
   */
  wwids?: string[];
}
