// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * ScalingModifiers describes advanced scaling logic options like formula
 *
 * @export
 */
export interface ScaledObjectSpecAdvancedScalingModifiers {
  /** activationTarget
   *
   * @required {false}
   */
  activationTarget?: string;
  /** formula
   *
   * @required {false}
   */
  formula?: string;
  /** metricType
   * MetricTargetType specifies the type of metric being targeted, and should be either
"Value", "AverageValue", or "Utilization"
   *
   * @required {false}
   */
  metricType?: string;
  /** target
   *
   * @required {false}
   */
  target?: string;
}
