// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * PodDNSConfigOption defines DNS resolver options of a pod.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecDnsConfigOptions {
  /** name
   * Required.
   *
   * @required {false}
   */
  name?: string;
  /** value
   *
   * @required {false}
   */
  value?: string;
}
