// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * Fallback is the spec for fallback options
 *
 * @export
 */
export interface ScaledObjectSpecFallback {
  /** failureThreshold
   *
   * @required {true}
   * @format {int32}
   * @originalType {integer}
   */
  failureThreshold: number;
  /** replicas
   *
   * @required {true}
   * @format {int32}
   * @originalType {integer}
   */
  replicas: number;
}
