// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * azureDisk represents an Azure Data Disk mount on the host and bind mount to the pod.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecVolumesAzureDisk {
  /** cachingMode
   * cachingMode is the Host Caching mode: None, Read Only, Read Write.
   *
   * @required {false}
   */
  cachingMode?: string;
  /** diskName
   * diskName is the Name of the data disk in the blob storage
   *
   * @required {true}
   */
  diskName: string;
  /** diskURI
   * diskURI is the URI of data disk in the blob storage
   *
   * @required {true}
   */
  diskURI: string;
  /** fsType
   * fsType is Filesystem type to mount.
Must be a filesystem type supported by the host operating system.
Ex. "ext4", "xfs", "ntfs". Implicitly inferred to be "ext4" if unspecified.
   *
   * @required {false}
   */
  fsType?: string;
  /** kind
   * kind expected values are Shared: multiple blob disks per storage account  Dedicated: single blob disk per storage account  Managed: azure managed data disk (only in managed availability set). defaults to shared
   *
   * @required {false}
   */
  kind?: string;
  /** readOnly
   * readOnly Defaults to false (read/write). ReadOnly here will force
the ReadOnly setting in VolumeMounts.
   *
   * @required {false}
   */
  readOnly?: boolean;
}
