// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledObjectStatusConditions } from './ScaledObjectStatusConditions';
import { ScaledObjectStatusScaleTargetGVKR } from './ScaledObjectStatusScaleTargetGVKR';

/**
 * ScaledObjectStatus is the status for a ScaledObject resource
 *
 * @export
 */
export interface ScaledObjectStatus {
  /** compositeScalerName
   *
   * @required {false}
   */
  compositeScalerName?: string;
  /** conditions
   * Condition to store the condition state
   *
   * @required {false}
   */
  conditions?: ScaledObjectStatusConditions[];
  /** externalMetricNames
   *
   * @required {false}
   */
  externalMetricNames?: string[];
  /** health
   *
   * @required {false}
   * @originalType {ScaledObjectStatusHealth}
   */
  health?: {[key: string]: object};
  /** hpaName
   *
   * @required {false}
   */
  hpaName?: string;
  /** lastActiveTime
   *
   * @required {false}
   * @format {date-time}
   */
  lastActiveTime?: string;
  /** originalReplicaCount
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  originalReplicaCount?: number;
  /** pausedReplicaCount
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  pausedReplicaCount?: number;
  /** resourceMetricNames
   *
   * @required {false}
   */
  resourceMetricNames?: string[];
  /** scaleTargetGVKR
   * GroupVersionKindResource provides unified structure for schema.GroupVersionKind and Resource
   *
   * @required {false}
   */
  scaleTargetGVKR?: ScaledObjectStatusScaleTargetGVKR;
  /** scaleTargetKind
   *
   * @required {false}
   */
  scaleTargetKind?: string;
}
