// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecJobTargetRefTemplateSpecInitContainersEnvValueFrom } from './ScaledJobSpecJobTargetRefTemplateSpecInitContainersEnvValueFrom';

/**
 * EnvVar represents an environment variable present in a Container.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecInitContainersEnv {
  /** name
   * Name of the environment variable. Must be a C_IDENTIFIER.
   *
   * @required {true}
   */
  name: string;
  /** value
   * Variable references $(VAR_NAME) are expanded
using the previously defined environment variables in the container and
any service environment variables. If a variable cannot be resolved,
the reference in the input string will be unchanged. Double $$ are reduced
to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e.
"$$(VAR_NAME)" will produce the string literal "$(VAR_NAME)".
Escaped references will never be expanded, regardless of whether the variable
exists or not.
Defaults to "".
   *
   * @required {false}
   */
  value?: string;
  /** valueFrom
   * Source for the environment variable's value. Cannot be used if value is not empty.
   *
   * @required {false}
   */
  valueFrom?: ScaledJobSpecJobTargetRefTemplateSpecInitContainersEnvValueFrom;
}
