// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecJobTargetRefPodFailurePolicyRules } from './ScaledJobSpecJobTargetRefPodFailurePolicyRules';

/**
 * Specifies the policy of handling failed pods. In particular, it allows to
specify the set of actions and conditions which need to be
satisfied to take the associated action.
If empty, the default behaviour applies - the counter of failed pods,
represented by the jobs&#39;s .status.failed field, is incremented and it is
checked against the backoffLimit. This field cannot be used in combination
with restartPolicy&#x3D;OnFailure.


This field is beta-level. It can be used when the &#x60;JobPodFailurePolicy&#x60;
feature gate is enabled (enabled by default).
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefPodFailurePolicy {
  /** rules
   * PodFailurePolicyRule describes how a pod failure is handled when the requirements are met.
One of onExitCodes and onPodConditions, but not both, can be used in each rule.
   *
   * @required {true}
   */
  rules: ScaledJobSpecJobTargetRefPodFailurePolicyRules[];
}
