// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledObjectSpecAdvancedHorizontalPodAutoscalerConfigBehaviorScaleDownPolicies } from './ScaledObjectSpecAdvancedHorizontalPodAutoscalerConfigBehaviorScaleDownPolicies';

/**
 * scaleDown is scaling policy for scaling Down.
If not set, the default value is to allow to scale down to minReplicas pods, with a
300 second stabilization window (i.e., the highest recommendation for
the last 300sec is used).
 *
 * @export
 */
export interface ScaledObjectSpecAdvancedHorizontalPodAutoscalerConfigBehaviorScaleDown {
  /** policies
   * HPAScalingPolicy is a single policy which must hold true for a specified past interval.
   *
   * @required {false}
   */
  policies?: ScaledObjectSpecAdvancedHorizontalPodAutoscalerConfigBehaviorScaleDownPolicies[];
  /** selectPolicy
   * selectPolicy is used to specify which policy should be used.
If not set, the default value Max is used.
   *
   * @required {false}
   */
  selectPolicy?: string;
  /** stabilizationWindowSeconds
   * stabilizationWindowSeconds is the number of seconds for which past recommendations should be
considered while scaling up or scaling down.
StabilizationWindowSeconds must be greater than or equal to zero and less than or equal to 3600 (one hour).
If not set, use the default values:
- For scale up: 0 (i.e. no stabilization is done).
- For scale down: 300 (i.e. the stabilization window is 300 seconds long).
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  stabilizationWindowSeconds?: number;
}
