// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * Exec specifies the action to take.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecInitContainersLifecyclePreStopExec {
  /** command
   *
   * @required {false}
   */
  command?: string[];
}
