// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecJobTargetRefTemplateSpecInitContainersLifecyclePostStartExec } from './ScaledJobSpecJobTargetRefTemplateSpecInitContainersLifecyclePostStartExec';
import { ScaledJobSpecJobTargetRefTemplateSpecInitContainersLifecyclePostStartHttpGet } from './ScaledJobSpecJobTargetRefTemplateSpecInitContainersLifecyclePostStartHttpGet';
import { ScaledJobSpecJobTargetRefTemplateSpecInitContainersLifecyclePostStartSleep } from './ScaledJobSpecJobTargetRefTemplateSpecInitContainersLifecyclePostStartSleep';
import { ScaledJobSpecJobTargetRefTemplateSpecInitContainersLifecyclePostStartTcpSocket } from './ScaledJobSpecJobTargetRefTemplateSpecInitContainersLifecyclePostStartTcpSocket';

/**
 * PostStart is called immediately after a container is created. If the handler fails,
the container is terminated and restarted according to its restart policy.
Other management of the container blocks until the hook completes.
More info: https:&#x2F;&#x2F;kubernetes.io&#x2F;docs&#x2F;concepts&#x2F;containers&#x2F;container-lifecycle-hooks&#x2F;#container-hooks
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecInitContainersLifecyclePostStart {
  /** exec
   * Exec specifies the action to take.
   *
   * @required {false}
   */
  exec?: ScaledJobSpecJobTargetRefTemplateSpecInitContainersLifecyclePostStartExec;
  /** httpGet
   * HTTPGet specifies the http request to perform.
   *
   * @required {false}
   */
  httpGet?: ScaledJobSpecJobTargetRefTemplateSpecInitContainersLifecyclePostStartHttpGet;
  /** sleep
   * Sleep represents the duration that the container should sleep before being terminated.
   *
   * @required {false}
   */
  sleep?: ScaledJobSpecJobTargetRefTemplateSpecInitContainersLifecyclePostStartSleep;
  /** tcpSocket
   * Deprecated. TCPSocket is NOT supported as a LifecycleHandler and kept
for the backward compatibility. There are no validation of this field and
lifecycle hooks will fail in runtime when tcp handler is specified.
   *
   * @required {false}
   */
  tcpSocket?: ScaledJobSpecJobTargetRefTemplateSpecInitContainersLifecyclePostStartTcpSocket;
}
