// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledObjectSpecAdvancedHorizontalPodAutoscalerConfigBehaviorScaleUpPolicies } from './ScaledObjectSpecAdvancedHorizontalPodAutoscalerConfigBehaviorScaleUpPolicies';

/**
 * scaleUp is scaling policy for scaling Up.
If not set, the default value is the higher of:
  * increase no more than 4 pods per 60 seconds
  * double the number of pods per 60 seconds
No stabilization is used.
 *
 * @export
 */
export interface ScaledObjectSpecAdvancedHorizontalPodAutoscalerConfigBehaviorScaleUp {
  /** policies
   * HPAScalingPolicy is a single policy which must hold true for a specified past interval.
   *
   * @required {false}
   */
  policies?: ScaledObjectSpecAdvancedHorizontalPodAutoscalerConfigBehaviorScaleUpPolicies[];
  /** selectPolicy
   * selectPolicy is used to specify which policy should be used.
If not set, the default value Max is used.
   *
   * @required {false}
   */
  selectPolicy?: string;
  /** stabilizationWindowSeconds
   * stabilizationWindowSeconds is the number of seconds for which past recommendations should be
considered while scaling up or scaling down.
StabilizationWindowSeconds must be greater than or equal to zero and less than or equal to 3600 (one hour).
If not set, use the default values:
- For scale up: 0 (i.e. no stabilization is done).
- For scale down: 300 (i.e. the stabilization window is 300 seconds long).
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  stabilizationWindowSeconds?: number;
}
