// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * PodSchedulingGate is associated to a Pod to guard its scheduling.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecSchedulingGates {
  /** name
   * Name of the scheduling gate.
Each scheduling gate must have a unique name field.
   *
   * @required {true}
   */
  name: string;
}
