// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * Represents the requirement on the container exit codes.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefPodFailurePolicyRulesOnExitCodes {
  /** containerName
   * Restricts the check for exit codes to the container with the
specified name. When null, the rule applies to all containers.
When specified, it should match one the container or initContainer
names in the pod template.
   *
   * @required {false}
   */
  containerName?: string;
  /** operator
   * Represents the relationship between the container exit code(s) and the
specified values. Containers completed with success (exit code 0) are
excluded from the requirement check. Possible values are:


- In: the requirement is satisfied if at least one container exit code
  (might be multiple if there are multiple containers not restricted
  by the 'containerName' field) is in the set of specified values.
- NotIn: the requirement is satisfied if at least one container exit code
  (might be multiple if there are multiple containers not restricted
  by the 'containerName' field) is not in the set of specified values.
Additional values are considered to be added in the future. Clients should
react to an unknown operator by assuming the requirement is not satisfied.
   *
   * @required {true}
   */
  operator: string;
  /** values
   *
   * @required {true}
   * @format {int32}
   * @originalType {integer}
   */
  values: number[];
}
