// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecJobTargetRefTemplateSpecEphemeralContainersResourcesClaims } from './ScaledJobSpecJobTargetRefTemplateSpecEphemeralContainersResourcesClaims';

/**
 * Resources are not allowed for ephemeral containers. Ephemeral containers use spare resources
already allocated to the pod.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecEphemeralContainersResources {
  /** claims
   * ResourceClaim references one entry in PodSpec.ResourceClaims.
   *
   * @required {false}
   */
  claims?: ScaledJobSpecJobTargetRefTemplateSpecEphemeralContainersResourcesClaims[];
  /** limits
   * Limits describes the maximum amount of compute resources allowed.
More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
   *
   * @required {false}
   */
  limits?: ScaledJobSpecJobTargetRefTemplateSpecEphemeralContainersResourcesLimits;
  /** requests
   * Requests describes the minimum amount of compute resources required.
If Requests is omitted for a container, it defaults to Limits if that is explicitly specified,
otherwise to an implementation-defined value. Requests cannot exceed Limits.
More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
   *
   * @required {false}
   */
  requests?: ScaledJobSpecJobTargetRefTemplateSpecEphemeralContainersResourcesRequests;
}
