// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecTriggersAuthenticationRef } from './ScaledJobSpecTriggersAuthenticationRef';

/**
 * ScaleTriggers reference the scaler that will be used
 *
 * @export
 */
export interface ScaledJobSpecTriggers {
  /** authenticationRef
   * AuthenticationRef points to the TriggerAuthentication or ClusterTriggerAuthentication object that
is used to authenticate the scaler with the environment
   *
   * @required {false}
   */
  authenticationRef?: ScaledJobSpecTriggersAuthenticationRef;
  /** metadata
   *
   * @required {true}
   * @originalType {ScaledJobSpecTriggersMetadata}
   */
  metadata: {[key: string]: string};
  /** name
   *
   * @required {false}
   */
  name?: string;
  /** type
   *
   * @required {true}
   */
  type: string;
  /** useCachedMetrics
   *
   * @required {false}
   */
  useCachedMetrics?: boolean;
}
