// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecJobTargetRefTemplateSpecContainersResourcesClaims } from './ScaledJobSpecJobTargetRefTemplateSpecContainersResourcesClaims';

/**
 * Compute Resources required by this container.
Cannot be updated.
More info: https:&#x2F;&#x2F;kubernetes.io&#x2F;docs&#x2F;concepts&#x2F;configuration&#x2F;manage-resources-containers&#x2F;
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecContainersResources {
  /** claims
   * ResourceClaim references one entry in PodSpec.ResourceClaims.
   *
   * @required {false}
   */
  claims?: ScaledJobSpecJobTargetRefTemplateSpecContainersResourcesClaims[];
  /** limits
   * Limits describes the maximum amount of compute resources allowed.
More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
   *
   * @required {false}
   */
  limits?: ScaledJobSpecJobTargetRefTemplateSpecContainersResourcesLimits;
  /** requests
   * Requests describes the minimum amount of compute resources required.
If Requests is omitted for a container, it defaults to Limits if that is explicitly specified,
otherwise to an implementation-defined value. Requests cannot exceed Limits.
More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
   *
   * @required {false}
   */
  requests?: ScaledJobSpecJobTargetRefTemplateSpecContainersResourcesRequests;
}
