// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesDownwardAPIItems } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesDownwardAPIItems';

/**
 * downwardAPI information about the downwardAPI data to project
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesDownwardAPI {
  /** items
   * DownwardAPIVolumeFile represents information to create the file containing the pod field
   *
   * @required {false}
   */
  items?: ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesDownwardAPIItems[];
}
