// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecJobTargetRefTemplateSpecVolumesRbdSecretRef } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesRbdSecretRef';

/**
 * rbd represents a Rados Block Device mount on the host that shares a pod&#39;s lifetime.
More info: https:&#x2F;&#x2F;examples.k8s.io&#x2F;volumes&#x2F;rbd&#x2F;README.md
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecVolumesRbd {
  /** fsType
   * fsType is the filesystem type of the volume that you want to mount.
Tip: Ensure that the filesystem type is supported by the host operating system.
Examples: "ext4", "xfs", "ntfs". Implicitly inferred to be "ext4" if unspecified.
More info: https://kubernetes.io/docs/concepts/storage/volumes#rbd
TODO: how do we prevent errors in the filesystem from compromising the machine
   *
   * @required {false}
   */
  fsType?: string;
  /** image
   * image is the rados image name.
More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it
   *
   * @required {true}
   */
  image: string;
  /** keyring
   * keyring is the path to key ring for RBDUser.
Default is /etc/ceph/keyring.
More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it
   *
   * @required {false}
   */
  keyring?: string;
  /** monitors
   *
   * @required {true}
   */
  monitors: string[];
  /** pool
   * pool is the rados pool name.
Default is rbd.
More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it
   *
   * @required {false}
   */
  pool?: string;
  /** readOnly
   * readOnly here will force the ReadOnly setting in VolumeMounts.
Defaults to false.
More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it
   *
   * @required {false}
   */
  readOnly?: boolean;
  /** secretRef
   * secretRef is name of the authentication secret for RBDUser. If provided
overrides keyring.
Default is nil.
More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it
   *
   * @required {false}
   */
  secretRef?: ScaledJobSpecJobTargetRefTemplateSpecVolumesRbdSecretRef;
  /** user
   * user is the rados user name.
Default is admin.
More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it
   *
   * @required {false}
   */
  user?: string;
}
