// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * portworxVolume represents a portworx volume attached and mounted on kubelets host machine
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecVolumesPortworxVolume {
  /** fsType
   * fSType represents the filesystem type to mount
Must be a filesystem type supported by the host operating system.
Ex. "ext4", "xfs". Implicitly inferred to be "ext4" if unspecified.
   *
   * @required {false}
   */
  fsType?: string;
  /** readOnly
   * readOnly defaults to false (read/write). ReadOnly here will force
the ReadOnly setting in VolumeMounts.
   *
   * @required {false}
   */
  readOnly?: boolean;
  /** volumeID
   * volumeID uniquely identifies a Portworx volume
   *
   * @required {true}
   */
  volumeID: string;
}
