// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * Selects a key of a secret in the pod&#39;s namespace
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecContainersEnvValueFromSecretKeyRef {
  /** key
   * The key of the secret to select from.  Must be a valid secret key.
   *
   * @required {true}
   */
  key: string;
  /** name
   * Name of the referent.
More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
TODO: Add other useful fields. apiVersion, kind, uid?
   *
   * @required {false}
   */
  name?: string;
  /** optional
   * Specify whether the Secret or its key must be defined
   *
   * @required {false}
   */
  optional?: boolean;
}
