// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * The seccomp options to use by the containers in this pod.
Note that this field cannot be set when spec.os.name is windows.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecSecurityContextSeccompProfile {
  /** localhostProfile
   * localhostProfile indicates a profile defined in a file on the node should be used.
The profile must be preconfigured on the node to work.
Must be a descending path, relative to the kubelet's configured seccomp profile location.
Must be set if type is "Localhost". Must NOT be set for any other type.
   *
   * @required {false}
   */
  localhostProfile?: string;
  /** type
   * type indicates which kind of seccomp profile will be applied.
Valid options are:


Localhost - a profile defined in a file on the node should be used.
RuntimeDefault - the container runtime default profile should be used.
Unconfined - no profile should be applied.
   *
   * @required {true}
   */
  type: string;
}
