// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobStatusConditions } from './ScaledJobStatusConditions';

/**
 * ScaledJobStatus defines the observed state of ScaledJob
 *
 * @export
 */
export interface ScaledJobStatus {
  /** Paused
   *
   * @required {false}
   */
  Paused?: string;
  /** conditions
   * Condition to store the condition state
   *
   * @required {false}
   */
  conditions?: ScaledJobStatusConditions[];
  /** lastActiveTime
   *
   * @required {false}
   * @format {date-time}
   */
  lastActiveTime?: string;
}
