// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * PodReadinessGate contains the reference to a pod condition
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecReadinessGates {
  /** conditionType
   * ConditionType refers to a condition in the pod's condition list with matching type.
   *
   * @required {true}
   */
  conditionType: string;
}
