// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesClusterTrustBundle } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesClusterTrustBundle';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesConfigMap } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesConfigMap';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesDownwardAPI } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesDownwardAPI';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesSecret } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesSecret';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesServiceAccountToken } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesServiceAccountToken';

/**
 * Projection that may be projected along with other supported volume types
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSources {
  /** clusterTrustBundle
   * ClusterTrustBundle allows a pod to access the `.spec.trustBundle` field
of ClusterTrustBundle objects in an auto-updating file.


Alpha, gated by the ClusterTrustBundleProjection feature gate.


ClusterTrustBundle objects can either be selected by name, or by the
combination of signer name and a label selector.


Kubelet performs aggressive normalization of the PEM contents written
into the pod filesystem.  Esoteric PEM features such as inter-block
comments and block headers are stripped.  Certificates are deduplicated.
The ordering of certificates within the file is arbitrary, and Kubelet
may change the order over time.
   *
   * @required {false}
   */
  clusterTrustBundle?: ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesClusterTrustBundle;
  /** configMap
   * configMap information about the configMap data to project
   *
   * @required {false}
   */
  configMap?: ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesConfigMap;
  /** downwardAPI
   * downwardAPI information about the downwardAPI data to project
   *
   * @required {false}
   */
  downwardAPI?: ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesDownwardAPI;
  /** secret
   * secret information about the secret data to project
   *
   * @required {false}
   */
  secret?: ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesSecret;
  /** serviceAccountToken
   * serviceAccountToken is information about the serviceAccountToken data to project
   *
   * @required {false}
   */
  serviceAccountToken?: ScaledJobSpecJobTargetRefTemplateSpecVolumesProjectedSourcesServiceAccountToken;
}
