// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecJobTargetRefTemplateSpecVolumesAwsElasticBlockStore } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesAwsElasticBlockStore';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesAzureDisk } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesAzureDisk';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesAzureFile } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesAzureFile';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesCephfs } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesCephfs';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesCinder } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesCinder';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesConfigMap } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesConfigMap';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesCsi } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesCsi';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesDownwardAPI } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesDownwardAPI';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesEmptyDir } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesEmptyDir';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesEphemeral } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesEphemeral';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesFc } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesFc';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesFlexVolume } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesFlexVolume';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesFlocker } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesFlocker';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesGcePersistentDisk } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesGcePersistentDisk';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesGitRepo } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesGitRepo';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesGlusterfs } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesGlusterfs';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesHostPath } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesHostPath';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesIscsi } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesIscsi';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesNfs } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesNfs';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesPersistentVolumeClaim } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesPersistentVolumeClaim';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesPhotonPersistentDisk } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesPhotonPersistentDisk';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesPortworxVolume } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesPortworxVolume';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesProjected } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesProjected';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesQuobyte } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesQuobyte';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesRbd } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesRbd';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesScaleIO } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesScaleIO';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesSecret } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesSecret';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesStorageos } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesStorageos';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumesVsphereVolume } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesVsphereVolume';

/**
 * Volume represents a named volume in a pod that may be accessed by any container in the pod.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecVolumes {
  /** awsElasticBlockStore
   * awsElasticBlockStore represents an AWS Disk resource that is attached to a
kubelet's host machine and then exposed to the pod.
More info: https://kubernetes.io/docs/concepts/storage/volumes#awselasticblockstore
   *
   * @required {false}
   */
  awsElasticBlockStore?: ScaledJobSpecJobTargetRefTemplateSpecVolumesAwsElasticBlockStore;
  /** azureDisk
   * azureDisk represents an Azure Data Disk mount on the host and bind mount to the pod.
   *
   * @required {false}
   */
  azureDisk?: ScaledJobSpecJobTargetRefTemplateSpecVolumesAzureDisk;
  /** azureFile
   * azureFile represents an Azure File Service mount on the host and bind mount to the pod.
   *
   * @required {false}
   */
  azureFile?: ScaledJobSpecJobTargetRefTemplateSpecVolumesAzureFile;
  /** cephfs
   * cephFS represents a Ceph FS mount on the host that shares a pod's lifetime
   *
   * @required {false}
   */
  cephfs?: ScaledJobSpecJobTargetRefTemplateSpecVolumesCephfs;
  /** cinder
   * cinder represents a cinder volume attached and mounted on kubelets host machine.
More info: https://examples.k8s.io/mysql-cinder-pd/README.md
   *
   * @required {false}
   */
  cinder?: ScaledJobSpecJobTargetRefTemplateSpecVolumesCinder;
  /** configMap
   * configMap represents a configMap that should populate this volume
   *
   * @required {false}
   */
  configMap?: ScaledJobSpecJobTargetRefTemplateSpecVolumesConfigMap;
  /** csi
   * csi (Container Storage Interface) represents ephemeral storage that is handled by certain external CSI drivers (Beta feature).
   *
   * @required {false}
   */
  csi?: ScaledJobSpecJobTargetRefTemplateSpecVolumesCsi;
  /** downwardAPI
   * downwardAPI represents downward API about the pod that should populate this volume
   *
   * @required {false}
   */
  downwardAPI?: ScaledJobSpecJobTargetRefTemplateSpecVolumesDownwardAPI;
  /** emptyDir
   * emptyDir represents a temporary directory that shares a pod's lifetime.
More info: https://kubernetes.io/docs/concepts/storage/volumes#emptydir
   *
   * @required {false}
   */
  emptyDir?: ScaledJobSpecJobTargetRefTemplateSpecVolumesEmptyDir;
  /** ephemeral
   * ephemeral represents a volume that is handled by a cluster storage driver.
The volume's lifecycle is tied to the pod that defines it - it will be created before the pod starts,
and deleted when the pod is removed.


Use this if:
a) the volume is only needed while the pod runs,
b) features of normal volumes like restoring from snapshot or capacity
   tracking are needed,
c) the storage driver is specified through a storage class, and
d) the storage driver supports dynamic volume provisioning through
   a PersistentVolumeClaim (see EphemeralVolumeSource for more
   information on the connection between this volume type
   and PersistentVolumeClaim).


Use PersistentVolumeClaim or one of the vendor-specific
APIs for volumes that persist for longer than the lifecycle
of an individual pod.


Use CSI for light-weight local ephemeral volumes if the CSI driver is meant to
be used that way - see the documentation of the driver for
more information.


A pod can use both types of ephemeral volumes and
persistent volumes at the same time.
   *
   * @required {false}
   */
  ephemeral?: ScaledJobSpecJobTargetRefTemplateSpecVolumesEphemeral;
  /** fc
   * fc represents a Fibre Channel resource that is attached to a kubelet's host machine and then exposed to the pod.
   *
   * @required {false}
   */
  fc?: ScaledJobSpecJobTargetRefTemplateSpecVolumesFc;
  /** flexVolume
   * flexVolume represents a generic volume resource that is
provisioned/attached using an exec based plugin.
   *
   * @required {false}
   */
  flexVolume?: ScaledJobSpecJobTargetRefTemplateSpecVolumesFlexVolume;
  /** flocker
   * flocker represents a Flocker volume attached to a kubelet's host machine. This depends on the Flocker control service being running
   *
   * @required {false}
   */
  flocker?: ScaledJobSpecJobTargetRefTemplateSpecVolumesFlocker;
  /** gcePersistentDisk
   * gcePersistentDisk represents a GCE Disk resource that is attached to a
kubelet's host machine and then exposed to the pod.
More info: https://kubernetes.io/docs/concepts/storage/volumes#gcepersistentdisk
   *
   * @required {false}
   */
  gcePersistentDisk?: ScaledJobSpecJobTargetRefTemplateSpecVolumesGcePersistentDisk;
  /** gitRepo
   * gitRepo represents a git repository at a particular revision.
DEPRECATED: GitRepo is deprecated. To provision a container with a git repo, mount an
EmptyDir into an InitContainer that clones the repo using git, then mount the EmptyDir
into the Pod's container.
   *
   * @required {false}
   */
  gitRepo?: ScaledJobSpecJobTargetRefTemplateSpecVolumesGitRepo;
  /** glusterfs
   * glusterfs represents a Glusterfs mount on the host that shares a pod's lifetime.
More info: https://examples.k8s.io/volumes/glusterfs/README.md
   *
   * @required {false}
   */
  glusterfs?: ScaledJobSpecJobTargetRefTemplateSpecVolumesGlusterfs;
  /** hostPath
   * hostPath represents a pre-existing file or directory on the host
machine that is directly exposed to the container. This is generally
used for system agents or other privileged things that are allowed
to see the host machine. Most containers will NOT need this.
More info: https://kubernetes.io/docs/concepts/storage/volumes#hostpath
---
TODO(jonesdl) We need to restrict who can use host directory mounts and who can/can not
mount host directories as read/write.
   *
   * @required {false}
   */
  hostPath?: ScaledJobSpecJobTargetRefTemplateSpecVolumesHostPath;
  /** iscsi
   * iscsi represents an ISCSI Disk resource that is attached to a
kubelet's host machine and then exposed to the pod.
More info: https://examples.k8s.io/volumes/iscsi/README.md
   *
   * @required {false}
   */
  iscsi?: ScaledJobSpecJobTargetRefTemplateSpecVolumesIscsi;
  /** name
   * name of the volume.
Must be a DNS_LABEL and unique within the pod.
More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
   *
   * @required {true}
   */
  name: string;
  /** nfs
   * nfs represents an NFS mount on the host that shares a pod's lifetime
More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs
   *
   * @required {false}
   */
  nfs?: ScaledJobSpecJobTargetRefTemplateSpecVolumesNfs;
  /** persistentVolumeClaim
   * persistentVolumeClaimVolumeSource represents a reference to a
PersistentVolumeClaim in the same namespace.
More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#persistentvolumeclaims
   *
   * @required {false}
   */
  persistentVolumeClaim?: ScaledJobSpecJobTargetRefTemplateSpecVolumesPersistentVolumeClaim;
  /** photonPersistentDisk
   * photonPersistentDisk represents a PhotonController persistent disk attached and mounted on kubelets host machine
   *
   * @required {false}
   */
  photonPersistentDisk?: ScaledJobSpecJobTargetRefTemplateSpecVolumesPhotonPersistentDisk;
  /** portworxVolume
   * portworxVolume represents a portworx volume attached and mounted on kubelets host machine
   *
   * @required {false}
   */
  portworxVolume?: ScaledJobSpecJobTargetRefTemplateSpecVolumesPortworxVolume;
  /** projected
   * projected items for all in one resources secrets, configmaps, and downward API
   *
   * @required {false}
   */
  projected?: ScaledJobSpecJobTargetRefTemplateSpecVolumesProjected;
  /** quobyte
   * quobyte represents a Quobyte mount on the host that shares a pod's lifetime
   *
   * @required {false}
   */
  quobyte?: ScaledJobSpecJobTargetRefTemplateSpecVolumesQuobyte;
  /** rbd
   * rbd represents a Rados Block Device mount on the host that shares a pod's lifetime.
More info: https://examples.k8s.io/volumes/rbd/README.md
   *
   * @required {false}
   */
  rbd?: ScaledJobSpecJobTargetRefTemplateSpecVolumesRbd;
  /** scaleIO
   * scaleIO represents a ScaleIO persistent volume attached and mounted on Kubernetes nodes.
   *
   * @required {false}
   */
  scaleIO?: ScaledJobSpecJobTargetRefTemplateSpecVolumesScaleIO;
  /** secret
   * secret represents a secret that should populate this volume.
More info: https://kubernetes.io/docs/concepts/storage/volumes#secret
   *
   * @required {false}
   */
  secret?: ScaledJobSpecJobTargetRefTemplateSpecVolumesSecret;
  /** storageos
   * storageOS represents a StorageOS volume attached and mounted on Kubernetes nodes.
   *
   * @required {false}
   */
  storageos?: ScaledJobSpecJobTargetRefTemplateSpecVolumesStorageos;
  /** vsphereVolume
   * vsphereVolume represents a vSphere volume attached and mounted on kubelets host machine
   *
   * @required {false}
   */
  vsphereVolume?: ScaledJobSpecJobTargetRefTemplateSpecVolumesVsphereVolume;
}
