// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledObjectSpecAdvancedHorizontalPodAutoscalerConfig } from './ScaledObjectSpecAdvancedHorizontalPodAutoscalerConfig';
import { ScaledObjectSpecAdvancedScalingModifiers } from './ScaledObjectSpecAdvancedScalingModifiers';

/**
 * AdvancedConfig specifies advance scaling options
 *
 * @export
 */
export interface ScaledObjectSpecAdvanced {
  /** horizontalPodAutoscalerConfig
   * HorizontalPodAutoscalerConfig specifies horizontal scale config
   *
   * @required {false}
   */
  horizontalPodAutoscalerConfig?: ScaledObjectSpecAdvancedHorizontalPodAutoscalerConfig;
  /** restoreToOriginalReplicaCount
   *
   * @required {false}
   */
  restoreToOriginalReplicaCount?: boolean;
  /** scalingModifiers
   * ScalingModifiers describes advanced scaling logic options like formula
   *
   * @required {false}
   */
  scalingModifiers?: ScaledObjectSpecAdvancedScalingModifiers;
}
