// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * azureFile represents an Azure File Service mount on the host and bind mount to the pod.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecVolumesAzureFile {
  /** readOnly
   * readOnly defaults to false (read/write). ReadOnly here will force
the ReadOnly setting in VolumeMounts.
   *
   * @required {false}
   */
  readOnly?: boolean;
  /** secretName
   * secretName is the  name of secret that contains Azure Storage Account Name and Key
   *
   * @required {true}
   */
  secretName: string;
  /** shareName
   * shareName is the azure share Name
   *
   * @required {true}
   */
  shareName: string;
}
