// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecJobTargetRefTemplateSpecAffinityNodeAffinity } from './ScaledJobSpecJobTargetRefTemplateSpecAffinityNodeAffinity';
import { ScaledJobSpecJobTargetRefTemplateSpecAffinityPodAffinity } from './ScaledJobSpecJobTargetRefTemplateSpecAffinityPodAffinity';
import { ScaledJobSpecJobTargetRefTemplateSpecAffinityPodAntiAffinity } from './ScaledJobSpecJobTargetRefTemplateSpecAffinityPodAntiAffinity';

/**
 * If specified, the pod&#39;s scheduling constraints
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecAffinity {
  /** nodeAffinity
   * Describes node affinity scheduling rules for the pod.
   *
   * @required {false}
   */
  nodeAffinity?: ScaledJobSpecJobTargetRefTemplateSpecAffinityNodeAffinity;
  /** podAffinity
   * Describes pod affinity scheduling rules (e.g. co-locate this pod in the same node, zone, etc. as some other pod(s)).
   *
   * @required {false}
   */
  podAffinity?: ScaledJobSpecJobTargetRefTemplateSpecAffinityPodAffinity;
  /** podAntiAffinity
   * Describes pod anti-affinity scheduling rules (e.g. avoid putting this pod in the same node, zone, etc. as some other pod(s)).
   *
   * @required {false}
   */
  podAntiAffinity?: ScaledJobSpecJobTargetRefTemplateSpecAffinityPodAntiAffinity;
}
