// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecJobTargetRefTemplateSpecVolumesCinderSecretRef } from './ScaledJobSpecJobTargetRefTemplateSpecVolumesCinderSecretRef';

/**
 * cinder represents a cinder volume attached and mounted on kubelets host machine.
More info: https:&#x2F;&#x2F;examples.k8s.io&#x2F;mysql-cinder-pd&#x2F;README.md
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecVolumesCinder {
  /** fsType
   * fsType is the filesystem type to mount.
Must be a filesystem type supported by the host operating system.
Examples: "ext4", "xfs", "ntfs". Implicitly inferred to be "ext4" if unspecified.
More info: https://examples.k8s.io/mysql-cinder-pd/README.md
   *
   * @required {false}
   */
  fsType?: string;
  /** readOnly
   * readOnly defaults to false (read/write). ReadOnly here will force
the ReadOnly setting in VolumeMounts.
More info: https://examples.k8s.io/mysql-cinder-pd/README.md
   *
   * @required {false}
   */
  readOnly?: boolean;
  /** secretRef
   * secretRef is optional: points to a secret object containing parameters used to connect
to OpenStack.
   *
   * @required {false}
   */
  secretRef?: ScaledJobSpecJobTargetRefTemplateSpecVolumesCinderSecretRef;
  /** volumeID
   * volumeID used to identify the volume in cinder.
More info: https://examples.k8s.io/mysql-cinder-pd/README.md
   *
   * @required {true}
   */
  volumeID: string;
}
