// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecJobTargetRefTemplateSpecAffinity } from './ScaledJobSpecJobTargetRefTemplateSpecAffinity';
import { ScaledJobSpecJobTargetRefTemplateSpecContainers } from './ScaledJobSpecJobTargetRefTemplateSpecContainers';
import { ScaledJobSpecJobTargetRefTemplateSpecDnsConfig } from './ScaledJobSpecJobTargetRefTemplateSpecDnsConfig';
import { ScaledJobSpecJobTargetRefTemplateSpecEphemeralContainers } from './ScaledJobSpecJobTargetRefTemplateSpecEphemeralContainers';
import { ScaledJobSpecJobTargetRefTemplateSpecHostAliases } from './ScaledJobSpecJobTargetRefTemplateSpecHostAliases';
import { ScaledJobSpecJobTargetRefTemplateSpecImagePullSecrets } from './ScaledJobSpecJobTargetRefTemplateSpecImagePullSecrets';
import { ScaledJobSpecJobTargetRefTemplateSpecInitContainers } from './ScaledJobSpecJobTargetRefTemplateSpecInitContainers';
import { ScaledJobSpecJobTargetRefTemplateSpecOs } from './ScaledJobSpecJobTargetRefTemplateSpecOs';
import { ScaledJobSpecJobTargetRefTemplateSpecReadinessGates } from './ScaledJobSpecJobTargetRefTemplateSpecReadinessGates';
import { ScaledJobSpecJobTargetRefTemplateSpecResourceClaims } from './ScaledJobSpecJobTargetRefTemplateSpecResourceClaims';
import { ScaledJobSpecJobTargetRefTemplateSpecSchedulingGates } from './ScaledJobSpecJobTargetRefTemplateSpecSchedulingGates';
import { ScaledJobSpecJobTargetRefTemplateSpecSecurityContext } from './ScaledJobSpecJobTargetRefTemplateSpecSecurityContext';
import { ScaledJobSpecJobTargetRefTemplateSpecTolerations } from './ScaledJobSpecJobTargetRefTemplateSpecTolerations';
import { ScaledJobSpecJobTargetRefTemplateSpecTopologySpreadConstraints } from './ScaledJobSpecJobTargetRefTemplateSpecTopologySpreadConstraints';
import { ScaledJobSpecJobTargetRefTemplateSpecVolumes } from './ScaledJobSpecJobTargetRefTemplateSpecVolumes';

/**
 * Specification of the desired behavior of the pod.
More info: https:&#x2F;&#x2F;git.k8s.io&#x2F;community&#x2F;contributors&#x2F;devel&#x2F;sig-architecture&#x2F;api-conventions.md#spec-and-status
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpec {
  /** activeDeadlineSeconds
   * Optional duration in seconds the pod may be active on the node relative to
StartTime before the system will actively try to mark it failed and kill associated containers.
Value must be a positive integer.
   *
   * @required {false}
   * @format {int64}
   * @originalType {integer}
   */
  activeDeadlineSeconds?: number;
  /** affinity
   * If specified, the pod's scheduling constraints
   *
   * @required {false}
   */
  affinity?: ScaledJobSpecJobTargetRefTemplateSpecAffinity;
  /** automountServiceAccountToken
   * AutomountServiceAccountToken indicates whether a service account token should be automatically mounted.
   *
   * @required {false}
   */
  automountServiceAccountToken?: boolean;
  /** containers
   * A single application container that you want to run within a pod.
   *
   * @required {true}
   */
  containers: ScaledJobSpecJobTargetRefTemplateSpecContainers[];
  /** dnsConfig
   * Specifies the DNS parameters of a pod.
Parameters specified here will be merged to the generated DNS
configuration based on DNSPolicy.
   *
   * @required {false}
   */
  dnsConfig?: ScaledJobSpecJobTargetRefTemplateSpecDnsConfig;
  /** dnsPolicy
   * Set DNS policy for the pod.
Defaults to "ClusterFirst".
Valid values are 'ClusterFirstWithHostNet', 'ClusterFirst', 'Default' or 'None'.
DNS parameters given in DNSConfig will be merged with the policy selected with DNSPolicy.
To have DNS options set along with hostNetwork, you have to specify DNS policy
explicitly to 'ClusterFirstWithHostNet'.
   *
   * @required {false}
   */
  dnsPolicy?: string;
  /** enableServiceLinks
   * EnableServiceLinks indicates whether information about services should be injected into pod's
environment variables, matching the syntax of Docker links.
Optional: Defaults to true.
   *
   * @required {false}
   */
  enableServiceLinks?: boolean;
  /** ephemeralContainers
   * An EphemeralContainer is a temporary container that you may add to an existing Pod for
user-initiated activities such as debugging. Ephemeral containers have no resource or
scheduling guarantees, and they will not be restarted when they exit or when a Pod is
removed or restarted. The kubelet may evict a Pod if an ephemeral container causes the
Pod to exceed its resource allocation.


To add an ephemeral container, use the ephemeralcontainers subresource of an existing
Pod. Ephemeral containers may not be removed or restarted.
   *
   * @required {false}
   */
  ephemeralContainers?: ScaledJobSpecJobTargetRefTemplateSpecEphemeralContainers[];
  /** hostAliases
   * HostAlias holds the mapping between IP and hostnames that will be injected as an entry in the
pod's hosts file.
   *
   * @required {false}
   */
  hostAliases?: ScaledJobSpecJobTargetRefTemplateSpecHostAliases[];
  /** hostIPC
   * Use the host's ipc namespace.
Optional: Default to false.
   *
   * @required {false}
   */
  hostIPC?: boolean;
  /** hostNetwork
   * Host networking requested for this pod. Use the host's network namespace.
If this option is set, the ports that will be used must be specified.
Default to false.
   *
   * @required {false}
   */
  hostNetwork?: boolean;
  /** hostPID
   * Use the host's pid namespace.
Optional: Default to false.
   *
   * @required {false}
   */
  hostPID?: boolean;
  /** hostUsers
   * Use the host's user namespace.
Optional: Default to true.
If set to true or not present, the pod will be run in the host user namespace, useful
for when the pod needs a feature only available to the host user namespace, such as
loading a kernel module with CAP_SYS_MODULE.
When set to false, a new userns is created for the pod. Setting false is useful for
mitigating container breakout vulnerabilities even allowing users to run their
containers as root without actually having root privileges on the host.
This field is alpha-level and is only honored by servers that enable the UserNamespacesSupport feature.
   *
   * @required {false}
   */
  hostUsers?: boolean;
  /** hostname
   * Specifies the hostname of the Pod
If not specified, the pod's hostname will be set to a system-defined value.
   *
   * @required {false}
   */
  hostname?: string;
  /** imagePullSecrets
   * LocalObjectReference contains enough information to let you locate the
referenced object inside the same namespace.
   *
   * @required {false}
   */
  imagePullSecrets?: ScaledJobSpecJobTargetRefTemplateSpecImagePullSecrets[];
  /** initContainers
   * A single application container that you want to run within a pod.
   *
   * @required {false}
   */
  initContainers?: ScaledJobSpecJobTargetRefTemplateSpecInitContainers[];
  /** nodeName
   * NodeName is a request to schedule this pod onto a specific node. If it is non-empty,
the scheduler simply schedules this pod onto that node, assuming that it fits resource
requirements.
   *
   * @required {false}
   */
  nodeName?: string;
  /** nodeSelector
   * NodeSelector is a selector which must be true for the pod to fit on a node.
Selector which must match a node's labels for the pod to be scheduled on that node.
More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
   *
   * @required {false}
   * @originalType {ScaledJobSpecJobTargetRefTemplateSpecNodeSelector}
   */
  nodeSelector?: {[key: string]: string};
  /** os
   * Specifies the OS of the containers in the pod.
Some pod and container fields are restricted if this is set.


If the OS field is set to linux, the following fields must be unset:
-securityContext.windowsOptions


If the OS field is set to windows, following fields must be unset:
- spec.hostPID
- spec.hostIPC
- spec.hostUsers
- spec.securityContext.seLinuxOptions
- spec.securityContext.seccompProfile
- spec.securityContext.fsGroup
- spec.securityContext.fsGroupChangePolicy
- spec.securityContext.sysctls
- spec.shareProcessNamespace
- spec.securityContext.runAsUser
- spec.securityContext.runAsGroup
- spec.securityContext.supplementalGroups
- spec.containers[*].securityContext.seLinuxOptions
- spec.containers[*].securityContext.seccompProfile
- spec.containers[*].securityContext.capabilities
- spec.containers[*].securityContext.readOnlyRootFilesystem
- spec.containers[*].securityContext.privileged
- spec.containers[*].securityContext.allowPrivilegeEscalation
- spec.containers[*].securityContext.procMount
- spec.containers[*].securityContext.runAsUser
- spec.containers[*].securityContext.runAsGroup
   *
   * @required {false}
   */
  os?: ScaledJobSpecJobTargetRefTemplateSpecOs;
  /** overhead
   * Overhead represents the resource overhead associated with running a pod for a given RuntimeClass.
This field will be autopopulated at admission time by the RuntimeClass admission controller. If
the RuntimeClass admission controller is enabled, overhead must not be set in Pod create requests.
The RuntimeClass admission controller will reject Pod create requests which have the overhead already
set. If RuntimeClass is configured and selected in the PodSpec, Overhead will be set to the value
defined in the corresponding RuntimeClass, otherwise it will remain unset and treated as zero.
More info: https://git.k8s.io/enhancements/keps/sig-node/688-pod-overhead/README.md
   *
   * @required {false}
   */
  overhead?: ScaledJobSpecJobTargetRefTemplateSpecOverhead;
  /** preemptionPolicy
   * PreemptionPolicy is the Policy for preempting pods with lower priority.
One of Never, PreemptLowerPriority.
Defaults to PreemptLowerPriority if unset.
   *
   * @required {false}
   */
  preemptionPolicy?: string;
  /** priority
   * The priority value. Various system components use this field to find the
priority of the pod. When Priority Admission Controller is enabled, it
prevents users from setting this field. The admission controller populates
this field from PriorityClassName.
The higher the value, the higher the priority.
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  priority?: number;
  /** priorityClassName
   * If specified, indicates the pod's priority. "system-node-critical" and
"system-cluster-critical" are two special keywords which indicate the
highest priorities with the former being the highest priority. Any other
name must be defined by creating a PriorityClass object with that name.
If not specified, the pod priority will be default or zero if there is no
default.
   *
   * @required {false}
   */
  priorityClassName?: string;
  /** readinessGates
   * PodReadinessGate contains the reference to a pod condition
   *
   * @required {false}
   */
  readinessGates?: ScaledJobSpecJobTargetRefTemplateSpecReadinessGates[];
  /** resourceClaims
   * PodResourceClaim references exactly one ResourceClaim through a ClaimSource.
It adds a name to it that uniquely identifies the ResourceClaim inside the Pod.
Containers that need access to the ResourceClaim reference it with this name.
   *
   * @required {false}
   */
  resourceClaims?: ScaledJobSpecJobTargetRefTemplateSpecResourceClaims[];
  /** restartPolicy
   * Restart policy for all containers within the pod.
One of Always, OnFailure, Never. In some contexts, only a subset of those values may be permitted.
Default to Always.
More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy
   *
   * @required {false}
   */
  restartPolicy?: string;
  /** runtimeClassName
   * RuntimeClassName refers to a RuntimeClass object in the node.k8s.io group, which should be used
to run this pod.  If no RuntimeClass resource matches the named class, the pod will not be run.
If unset or empty, the "legacy" RuntimeClass will be used, which is an implicit class with an
empty definition that uses the default runtime handler.
More info: https://git.k8s.io/enhancements/keps/sig-node/585-runtime-class
   *
   * @required {false}
   */
  runtimeClassName?: string;
  /** schedulerName
   * If specified, the pod will be dispatched by specified scheduler.
If not specified, the pod will be dispatched by default scheduler.
   *
   * @required {false}
   */
  schedulerName?: string;
  /** schedulingGates
   * PodSchedulingGate is associated to a Pod to guard its scheduling.
   *
   * @required {false}
   */
  schedulingGates?: ScaledJobSpecJobTargetRefTemplateSpecSchedulingGates[];
  /** securityContext
   * SecurityContext holds pod-level security attributes and common container settings.
Optional: Defaults to empty.  See type description for default values of each field.
   *
   * @required {false}
   */
  securityContext?: ScaledJobSpecJobTargetRefTemplateSpecSecurityContext;
  /** serviceAccount
   * DeprecatedServiceAccount is a depreciated alias for ServiceAccountName.
Deprecated: Use serviceAccountName instead.
   *
   * @required {false}
   */
  serviceAccount?: string;
  /** serviceAccountName
   * ServiceAccountName is the name of the ServiceAccount to use to run this pod.
More info: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
   *
   * @required {false}
   */
  serviceAccountName?: string;
  /** setHostnameAsFQDN
   * If true the pod's hostname will be configured as the pod's FQDN, rather than the leaf name (the default).
In Linux containers, this means setting the FQDN in the hostname field of the kernel (the nodename field of struct utsname).
In Windows containers, this means setting the registry value of hostname for the registry key HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters to FQDN.
If a pod does not have FQDN, this has no effect.
Default to false.
   *
   * @required {false}
   */
  setHostnameAsFQDN?: boolean;
  /** shareProcessNamespace
   * Share a single process namespace between all of the containers in a pod.
When this is set containers will be able to view and signal processes from other containers
in the same pod, and the first process in each container will not be assigned PID 1.
HostPID and ShareProcessNamespace cannot both be set.
Optional: Default to false.
   *
   * @required {false}
   */
  shareProcessNamespace?: boolean;
  /** subdomain
   * If specified, the fully qualified Pod hostname will be "<hostname>.<subdomain>.<pod namespace>.svc.<cluster domain>".
If not specified, the pod will not have a domainname at all.
   *
   * @required {false}
   */
  subdomain?: string;
  /** terminationGracePeriodSeconds
   * Optional duration in seconds the pod needs to terminate gracefully. May be decreased in delete request.
Value must be non-negative integer. The value zero indicates stop immediately via
the kill signal (no opportunity to shut down).
If this value is nil, the default grace period will be used instead.
The grace period is the duration in seconds after the processes running in the pod are sent
a termination signal and the time when the processes are forcibly halted with a kill signal.
Set this value longer than the expected cleanup time for your process.
Defaults to 30 seconds.
   *
   * @required {false}
   * @format {int64}
   * @originalType {integer}
   */
  terminationGracePeriodSeconds?: number;
  /** tolerations
   * The pod this Toleration is attached to tolerates any taint that matches
the triple <key,value,effect> using the matching operator <operator>.
   *
   * @required {false}
   */
  tolerations?: ScaledJobSpecJobTargetRefTemplateSpecTolerations[];
  /** topologySpreadConstraints
   * TopologySpreadConstraint specifies how to spread matching pods among the given topology.
   *
   * @required {false}
   */
  topologySpreadConstraints?: ScaledJobSpecJobTargetRefTemplateSpecTopologySpreadConstraints[];
  /** volumes
   * Volume represents a named volume in a pod that may be accessed by any container in the pod.
   *
   * @required {false}
   */
  volumes?: ScaledJobSpecJobTargetRefTemplateSpecVolumes[];
}
