// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledJobSpecJobTargetRefTemplateSpecDnsConfigOptions } from './ScaledJobSpecJobTargetRefTemplateSpecDnsConfigOptions';

/**
 * Specifies the DNS parameters of a pod.
Parameters specified here will be merged to the generated DNS
configuration based on DNSPolicy.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecDnsConfig {
  /** nameservers
   *
   * @required {false}
   */
  nameservers?: string[];
  /** options
   * PodDNSConfigOption defines DNS resolver options of a pod.
   *
   * @required {false}
   */
  options?: ScaledJobSpecJobTargetRefTemplateSpecDnsConfigOptions[];
  /** searches
   *
   * @required {false}
   */
  searches?: string[];
}
