// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * volumeDevice describes a mapping of a raw block device within a container.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecInitContainersVolumeDevices {
  /** devicePath
   * devicePath is the path inside of the container that the device will be mapped to.
   *
   * @required {true}
   */
  devicePath: string;
  /** name
   * name must match the name of a persistentVolumeClaim in the pod
   *
   * @required {true}
   */
  name: string;
}
