// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * ContainerPort represents a network port in a single container.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefTemplateSpecEphemeralContainersPorts {
  /** containerPort
   * Number of port to expose on the pod's IP address.
This must be a valid port number, 0 < x < 65536.
   *
   * @required {true}
   * @format {int32}
   * @originalType {integer}
   */
  containerPort: number;
  /** hostIP
   * What host IP to bind the external port to.
   *
   * @required {false}
   */
  hostIP?: string;
  /** hostPort
   * Number of port to expose on the host.
If specified, this must be a valid port number, 0 < x < 65536.
If HostNetwork is specified, this must match ContainerPort.
Most containers do not need this.
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  hostPort?: number;
  /** name
   * If specified, this must be an IANA_SVC_NAME and unique within the pod. Each
named port in a pod must have a unique name. Name for the port that can be
referred to by services.
   *
   * @required {false}
   */
  name?: string;
  /** protocol
   * Protocol for port. Must be UDP, TCP, or SCTP.
Defaults to "TCP".
   *
   * @required {true}
   * @required {TCP}
   */
  protocol: string;
}
