// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * PodFailurePolicyOnPodConditionsPattern describes a pattern for matching
an actual pod condition type.
 *
 * @export
 */
export interface ScaledJobSpecJobTargetRefPodFailurePolicyRulesOnPodConditions {
  /** status
   * Specifies the required Pod condition status. To match a pod condition
it is required that the specified status equals the pod condition status.
Defaults to True.
   *
   * @required {true}
   */
  status: string;
  /** type
   * Specifies the required Pod condition type. To match a pod condition
it is required that specified type equals the pod condition type.
   *
   * @required {true}
   */
  type: string;
}
