// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { ScaledObjectSpecAdvanced } from './ScaledObjectSpecAdvanced';
import { ScaledObjectSpecFallback } from './ScaledObjectSpecFallback';
import { ScaledObjectSpecScaleTargetRef } from './ScaledObjectSpecScaleTargetRef';
import { ScaledObjectSpecTriggers } from './ScaledObjectSpecTriggers';

/**
 * ScaledObjectSpec is the spec for a ScaledObject resource
 *
 * @export
 */
export interface ScaledObjectSpec {
  /** advanced
   * AdvancedConfig specifies advance scaling options
   *
   * @required {false}
   */
  advanced?: ScaledObjectSpecAdvanced;
  /** cooldownPeriod
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  cooldownPeriod?: number;
  /** fallback
   * Fallback is the spec for fallback options
   *
   * @required {false}
   */
  fallback?: ScaledObjectSpecFallback;
  /** idleReplicaCount
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  idleReplicaCount?: number;
  /** initialCooldownPeriod
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  initialCooldownPeriod?: number;
  /** maxReplicaCount
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  maxReplicaCount?: number;
  /** minReplicaCount
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  minReplicaCount?: number;
  /** pollingInterval
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  pollingInterval?: number;
  /** scaleTargetRef
   * ScaleTarget holds the reference to the scale target Object
   *
   * @required {true}
   */
  scaleTargetRef: ScaledObjectSpecScaleTargetRef;
  /** triggers
   * ScaleTriggers reference the scaler that will be used
   *
   * @required {true}
   */
  triggers: ScaledObjectSpecTriggers[];
}
