// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * HPAScalingPolicy is a single policy which must hold true for a specified past interval.
 *
 * @export
 */
export interface ScaledObjectSpecAdvancedHorizontalPodAutoscalerConfigBehaviorScaleUpPolicies {
  /** periodSeconds
   * periodSeconds specifies the window of time for which the policy should hold true.
PeriodSeconds must be greater than zero and less than or equal to 1800 (30 min).
   *
   * @required {true}
   * @format {int32}
   * @originalType {integer}
   */
  periodSeconds: number;
  /** type
   * type is used to specify the scaling policy.
   *
   * @required {true}
   */
  type: string;
  /** value
   * value contains the amount of change which is permitted by the policy.
It must be greater than zero
   *
   * @required {true}
   * @format {int32}
   * @originalType {integer}
   */
  value: number;
}
