// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { TriggerAuthenticationSpecHashiCorpVaultSecretsPkiData } from './TriggerAuthenticationSpecHashiCorpVaultSecretsPkiData';

/**
 * VaultSecret defines the mapping between the path of the secret in Vault to the parameter
 *
 * @export
 */
export interface TriggerAuthenticationSpecHashiCorpVaultSecrets {
  /** key
   *
   * @required {true}
   */
  key: string;
  /** parameter
   *
   * @required {true}
   */
  parameter: string;
  /** path
   *
   * @required {true}
   */
  path: string;
  /** pkiData
   *
   * @required {false}
   */
  pkiData?: TriggerAuthenticationSpecHashiCorpVaultSecretsPkiData;
  /** type
   * VaultSecretType defines the type of vault secret
   *
   * @required {false}
   */
  type?: string;
}
