// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { TriggerAuthenticationSpecHashiCorpVaultCredential } from './TriggerAuthenticationSpecHashiCorpVaultCredential';
import { TriggerAuthenticationSpecHashiCorpVaultSecrets } from './TriggerAuthenticationSpecHashiCorpVaultSecrets';

/**
 * HashiCorpVault is used to authenticate using Hashicorp Vault
 *
 * @export
 */
export interface TriggerAuthenticationSpecHashiCorpVault {
  /** address
   *
   * @required {true}
   */
  address: string;
  /** authentication
   * VaultAuthentication contains the list of Hashicorp Vault authentication methods
   *
   * @required {true}
   */
  authentication: string;
  /** credential
   * Credential defines the Hashicorp Vault credentials depending on the authentication method
   *
   * @required {false}
   */
  credential?: TriggerAuthenticationSpecHashiCorpVaultCredential;
  /** mount
   *
   * @required {false}
   */
  mount?: string;
  /** namespace
   *
   * @required {false}
   */
  namespace?: string;
  /** role
   *
   * @required {false}
   */
  role?: string;
  /** secrets
   * VaultSecret defines the mapping between the path of the secret in Vault to the parameter
   *
   * @required {true}
   */
  secrets: TriggerAuthenticationSpecHashiCorpVaultSecrets[];
}
