// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * Credential defines the Hashicorp Vault credentials depending on the authentication method
 *
 * @export
 */
export interface TriggerAuthenticationSpecHashiCorpVaultCredential {
  /** serviceAccount
   *
   * @required {false}
   */
  serviceAccount?: string;
  /** token
   *
   * @required {false}
   */
  token?: string;
}
