// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * AuthEnvironment is used to authenticate using environment variables
in the destination ScaleTarget spec
 *
 * @export
 */
export interface TriggerAuthenticationSpecEnv {
  /** containerName
   *
   * @required {false}
   */
  containerName?: string;
  /** name
   *
   * @required {true}
   */
  name: string;
  /** parameter
   *
   * @required {true}
   */
  parameter: string;
}
