// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { TriggerAuthenticationSpecAwsSecretManagerCredentials } from './TriggerAuthenticationSpecAwsSecretManagerCredentials';
import { TriggerAuthenticationSpecAwsSecretManagerPodIdentity } from './TriggerAuthenticationSpecAwsSecretManagerPodIdentity';
import { TriggerAuthenticationSpecAwsSecretManagerSecrets } from './TriggerAuthenticationSpecAwsSecretManagerSecrets';

/**
 * AwsSecretManager is used to authenticate using AwsSecretManager
 *
 * @export
 */
export interface TriggerAuthenticationSpecAwsSecretManager {
  /** credentials
   *
   * @required {false}
   */
  credentials?: TriggerAuthenticationSpecAwsSecretManagerCredentials;
  /** podIdentity
   * AuthPodIdentity allows users to select the platform native identity
mechanism
   *
   * @required {false}
   */
  podIdentity?: TriggerAuthenticationSpecAwsSecretManagerPodIdentity;
  /** region
   *
   * @required {false}
   */
  region?: string;
  /** secrets
   *
   * @required {true}
   */
  secrets: TriggerAuthenticationSpecAwsSecretManagerSecrets[];
}
