// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

export interface TriggerAuthenticationSpecAwsSecretManagerSecrets {
  /** name
   *
   * @required {true}
   */
  name: string;
  /** parameter
   *
   * @required {true}
   */
  parameter: string;
  /** versionId
   *
   * @required {false}
   */
  versionId?: string;
  /** versionStage
   *
   * @required {false}
   */
  versionStage?: string;
}
