// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * AuthConfigMapTargetRef is used to authenticate using a reference to a config map
 *
 * @export
 */
export interface TriggerAuthenticationSpecConfigMapTargetRef {
  /** key
   *
   * @required {true}
   */
  key: string;
  /** name
   *
   * @required {true}
   */
  name: string;
  /** parameter
   *
   * @required {true}
   */
  parameter: string;
}
