// @ts-nocheck
/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { TriggerAuthenticationSpecAzureKeyVaultCloud } from './TriggerAuthenticationSpecAzureKeyVaultCloud';
import { TriggerAuthenticationSpecAzureKeyVaultCredentials } from './TriggerAuthenticationSpecAzureKeyVaultCredentials';
import { TriggerAuthenticationSpecAzureKeyVaultPodIdentity } from './TriggerAuthenticationSpecAzureKeyVaultPodIdentity';
import { TriggerAuthenticationSpecAzureKeyVaultSecrets } from './TriggerAuthenticationSpecAzureKeyVaultSecrets';

/**
 * AzureKeyVault is used to authenticate using Azure Key Vault
 *
 * @export
 */
export interface TriggerAuthenticationSpecAzureKeyVault {
  /** cloud
   *
   * @required {false}
   */
  cloud?: TriggerAuthenticationSpecAzureKeyVaultCloud;
  /** credentials
   *
   * @required {false}
   */
  credentials?: TriggerAuthenticationSpecAzureKeyVaultCredentials;
  /** podIdentity
   * AuthPodIdentity allows users to select the platform native identity
mechanism
   *
   * @required {false}
   */
  podIdentity?: TriggerAuthenticationSpecAzureKeyVaultPodIdentity;
  /** secrets
   *
   * @required {true}
   */
  secrets: TriggerAuthenticationSpecAzureKeyVaultSecrets[];
  /** vaultUri
   *
   * @required {true}
   */
  vaultUri: string;
}
