changesetBaseRefs:
  - master
  - origin/master
  - upstream/master
  - main
  - origin/main
  - upstream/main
  - dev
  - origin/dev
  - upstream/dev

checksumBehavior: reset

enableImmutableInstalls: false

initScope: "@echobox"

nmMode: hardlinks-global

nodeLinker: node-modules

preferInteractive: true

preferReuse: true

winLinkType: symlinks
